// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NewsArticle struct {
	ID            int32            `db:"id" json:"id"`
	Title         string           `db:"title" json:"title"`
	Summary       string           `db:"summary" json:"summary"`
	Content       string           `db:"content" json:"content"`
	FeaturedImage pgtype.Text      `db:"featured_image" json:"featured_image"`
	CategoryID    int32            `db:"category_id" json:"category_id"`
	Status        string           `db:"status" json:"status"`
	PublishedAt   pgtype.Timestamp `db:"published_at" json:"published_at"`
	ViewsCount    pgtype.Int8      `db:"views_count" json:"views_count"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	SourceUrl     string           `db:"source_url" json:"source_url"`
}

type NewsCategory struct {
	ID        int32            `db:"id" json:"id"`
	Name      string           `db:"name" json:"name"`
	Slug      string           `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type NewsComment struct {
	ID         int32            `db:"id" json:"id"`
	ArticleID  int32            `db:"article_id" json:"article_id"`
	UserName   string           `db:"user_name" json:"user_name"`
	UserEmail  string           `db:"user_email" json:"user_email"`
	Content    string           `db:"content" json:"content"`
	IsApproved pgtype.Bool      `db:"is_approved" json:"is_approved"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type NewsUser struct {
	UserID    int32            `db:"user_id" json:"user_id"`
	UserName  string           `db:"user_name" json:"user_name"`
	Email     string           `db:"email" json:"email"`
	Phone     string           `db:"phone" json:"phone"`
	Pass      string           `db:"pass" json:"pass"`
	PssValid  bool             `db:"pss_valid" json:"pss_valid"`
	Otp       string           `db:"otp" json:"otp"`
	UserValid bool             `db:"user_valid" json:"user_valid"`
	OtpExp    pgtype.Timestamp `db:"otp_exp" json:"otp_exp"`
	Role      string           `db:"role" json:"role"`
}
