// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUser(ctx context.Context, email string) error
	ApprovalDueListOfComments(ctx context.Context) ([]ApprovalDueListOfCommentsRow, error)
	// OFFSET $1 LIMIT $2;
	ApproveArticle(ctx context.Context, id int32) error
	ApproveComment(ctx context.Context, id int32) (NewsComment, error)
	CheckCategoryExists(ctx context.Context, id int32) (bool, error)
	CheckCategoryInUse(ctx context.Context, categoryID int32) (bool, error)
	CheckCategorySlugExists(ctx context.Context, arg CheckCategorySlugExistsParams) (bool, error)
	// --------------------- Category DATA ------------------------------
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (NewsCategory, error)
	// ----------------- Comments Data ---------------------------------
	CreateCommentWithDefaults(ctx context.Context, arg CreateCommentWithDefaultsParams) (NewsComment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteCategory(ctx context.Context, id int32) error
	DisableComment(ctx context.Context, id int32) (NewsComment, error)
	DraftArticle(ctx context.Context, id int32) error
	GetAllCategory(ctx context.Context) ([]NewsCategory, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetApprovedBanArticles(ctx context.Context, arg GetApprovedBanArticlesParams) ([]NewsArticle, error)
	GetApprovedCommentsByArticle(ctx context.Context, articleID int32) ([]NewsComment, error)
	GetApprovedEngArticles(ctx context.Context, arg GetApprovedEngArticlesParams) ([]NewsArticle, error)
	// ------------------- Article Service ------------------------------
	GetArticleDetails(ctx context.Context, id int32) (NewsArticle, error)
	GetCategory(ctx context.Context, id int32) (NewsCategory, error)
	GetPendingComments(ctx context.Context) ([]NewsComment, error)
	GetTodaysBnNews(ctx context.Context, dollar_1 pgtype.Date) ([]NewsArticle, error)
	GetTodaysEnNews(ctx context.Context, dollar_1 pgtype.Date) ([]NewsArticle, error)
	GetUnApprovedArticleList(ctx context.Context) ([]NewsArticle, error)
	// --------------------- AUTHENTICATION ------------------------------
	GetUserByEmail(ctx context.Context, email string) (NewsUser, error)
	GetUserById(ctx context.Context, userID int32) (NewsUser, error)
	GetUserByLogin(ctx context.Context, userName string) (NewsUser, error)
	GetUserByPhone(ctx context.Context, phone string) (NewsUser, error)
	GetUserByUserName(ctx context.Context, userName string) (NewsUser, error)
	ReadArticleCount(ctx context.Context, id int32) error
	SendNewOtp(ctx context.Context, arg SendNewOtpParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (NewsCategory, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
